# Generated by Django 6.1 on 2026-09-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_url_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='click_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
