# Generated by Django 6.1 on 2026-09-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_url_click_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='custom_alias',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
