# Generated by Django 6.1 on 2026-09-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_url_custom_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
