# Generated by Django 6.1 on 2026-09-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_url_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='custom_alias',
        ),
        migrations.RemoveField(
            model_name='url',
            name='short_code',
        ),
        migrations.AlterField(
            model_name='url',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
